//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.23 at 12:21:02 PM UZT 
//


package org.sbs.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvecApi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvecApi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="marketstat" type="{}Marketstat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvecApi", propOrder = {
    "marketstat"
})
public class EvecApi {

    @XmlElement(required = true)
    protected Marketstat marketstat;

    /**
     * Gets the value of the marketstat property.
     * 
     * @return
     *     possible object is
     *     {@link org.sbs.xml.Marketstat }
     *     
     */
    public Marketstat getMarketstat() {
        return marketstat;
    }

    /**
     * Sets the value of the marketstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.sbs.xml.Marketstat }
     *     
     */
    public void setMarketstat(Marketstat value) {
        this.marketstat = value;
    }

}
